steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/icpgenerator/customer-profile-app', '--build-arg', 'VITE_API_KEY=$_VITE_API_KEY', '.' ]
images:
- 'gcr.io/icpgenerator/customer-profile-app'
substitutions:
  _VITE_API_KEY: ''
