import React, { useState } from 'react';
import { Download, FileText, Image as ImageIcon, Presentation, File, Loader2, ChevronDown } from 'lucide-react';
import { ICPData } from '../types';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import PptxGenJS from 'pptxgenjs';

interface ExportMenuProps {
  data: ICPData;
  elementRef: React.RefObject<HTMLDivElement>;
}

export const ExportMenu: React.FC<ExportMenuProps> = ({ data, elementRef }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const toggleOpen = () => setIsOpen(!isOpen);

  // 1. Export as Image (PNG)
  const handleExportImage = async () => {
    if (!elementRef.current) return;
    setIsExporting(true);
    setIsOpen(false);
    
    try {
      const canvas = await html2canvas(elementRef.current, {
        scale: 2,
        backgroundColor: '#f3f4f6',
        useCORS: true,
        logging: false,
        ignoreElements: (element) => element.classList.contains('no-export')
      });
      
      const link = document.createElement('a');
      link.download = `ICP-${data.targetName.replace(/\s+/g, '-')}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (err) {
      console.error("Image export failed", err);
      alert("Failed to export image. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  // 2. Export as PDF
  const handleExportPDF = async () => {
    if (!elementRef.current) return;
    setIsExporting(true);
    setIsOpen(false);

    try {
      // Wait a moment to ensure styles are settled
      await new Promise(resolve => setTimeout(resolve, 100));

      const element = elementRef.current;
      const canvas = await html2canvas(element, {
        scale: 2,
        backgroundColor: '#f3f4f6',
        useCORS: true,
        logging: false,
        // Ensure we capture the full scrollable height
        height: element.scrollHeight,
        windowHeight: element.scrollHeight,
        x: 0,
        y: 0,
        ignoreElements: (el) => el.classList.contains('no-export')
      });
      
      const imgData = canvas.toDataURL('image/png');
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;

      const pdf = new jsPDF({
        orientation: imgWidth > imgHeight ? 'landscape' : 'portrait',
        unit: 'px',
        format: [imgWidth, imgHeight]
      });

      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      pdf.save(`ICP-${data.targetName.replace(/\s+/g, '-')}.pdf`);
    } catch (err) {
      console.error("PDF export failed", err);
      alert("Failed to export PDF.");
    } finally {
      setIsExporting(false);
    }
  };

  // 3. Export as Word (HTML Blob)
  const handleExportWord = () => {
    setIsExporting(true);
    setIsOpen(false);

    try {
      const content = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head>
          <meta charset='utf-8'>
          <title>${data.targetName}</title>
          <style>
            body { font-family: 'Calibri', sans-serif; }
            h1 { color: #002452; font-size: 24pt; }
            h2 { color: #d97706; font-size: 18pt; margin-top: 20px; }
            h3 { color: #374151; font-size: 14pt; margin-top: 15px; }
            p { font-size: 11pt; }
            ul { margin-bottom: 10px; }
            li { margin-bottom: 5px; }
          </style>
        </head>
        <body>
          <h1>ICP Report: ${data.targetName}</h1>
          <p><strong>Generated by Blackwoods ICP Intelligence</strong></p>
          <hr/>
          
          <h2>Executive Summary</h2>
          <p>${data.summary}</p>

          <h2>Firmographics</h2>
          <ul>
            <li><strong>Company Size:</strong> ${data.firmographics.companySize}</li>
            <li><strong>Revenue:</strong> ${data.firmographics.revenueRange}</li>
            <li><strong>Facilities:</strong> ${data.firmographics.facilitiesCount}</li>
            <li><strong>Location:</strong> ${data.firmographics.geographicPresence}</li>
          </ul>

          <h2>Operational Profile</h2>
          <p><strong>Workforce:</strong> ${data.operationalIndicators.workforceSizePPE}</p>
          <p><strong>Risk Environment:</strong> ${data.operationalIndicators.riskEnvironment}</p>
          <p><strong>Complexity:</strong></p>
          <ul>${data.operationalIndicators.operatingConditions.map(c => `<li>${c}</li>`).join('')}</ul>
          
          <h2>Buying Signals</h2>
          <ul>${data.buyingSignals.map(s => `<li>[${s.urgency}] <strong>${s.signal}</strong>: ${s.description}</li>`).join('')}</ul>

          <h2>Key Pain Points</h2>
          <ul>${data.keyPainPoints.map(p => `<li>${p}</li>`).join('')}</ul>

          <h2>Decision Makers</h2>
          ${data.decisionMakers.map(dm => `
            <h3>${dm.role}</h3>
            <p>Priorities: ${dm.priorities.join(', ')}</p>
            <p>Pain Points: ${dm.painPoints.join(', ')}</p>
          `).join('')}

          <h2>Recommended Approach</h2>
          <ul>${data.recommendedApproach.map(r => `<li>${r}</li>`).join('')}</ul>

          <h2>Product Fit</h2>
          <p><strong>High Priority:</strong> ${data.productFit.highPriority.join(', ')}</p>
          <p><strong>Medium Priority:</strong> ${data.productFit.mediumPriority.join(', ')}</p>
          <p><strong>Cross-Sell:</strong> ${data.productFit.crossSell.join(', ')}</p>
        </body>
        </html>
      `;

      const blob = new Blob(['\ufeff', content], { type: 'application/msword' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `ICP-${data.targetName.replace(/\s+/g, '-')}.doc`;
      link.click();
    } catch (err) {
      console.error("Word export failed", err);
    } finally {
      setIsExporting(false);
    }
  };

  // 4. Export as PowerPoint
  const handleExportPPT = () => {
    setIsExporting(true);
    setIsOpen(false);

    try {
      const pres = new PptxGenJS();
      
      // Theme & Layout
      pres.layout = 'LAYOUT_16x9'; // 10 x 5.625 inches
      pres.theme = { headFontFace: 'Arial', bodyFontFace: 'Arial' };

      // Helper for brand colors
      const COLOR_BRAND = '002452';
      const COLOR_ACCENT = 'fbbf24'; // Amber
      const COLOR_TEXT = '374151';

      // --- Slide 1: Title ---
      let slide = pres.addSlide();
      slide.background = { color: COLOR_BRAND };
      slide.addText(data.targetName, { x: 0.5, y: '40%', w: '90%', fontSize: 36, color: 'FFFFFF', align: 'center', bold: true });
      slide.addText('Ideal Customer Profile Intelligence', { x: 0.5, y: '55%', w: '90%', fontSize: 18, color: COLOR_ACCENT, align: 'center' });
      slide.addText(`Generated on ${new Date().toLocaleDateString()}`, { x: 0.5, y: '85%', w: '90%', fontSize: 12, color: '9ca3af', align: 'center' });

      // --- Slide 2: Summary & Firmographics ---
      slide = pres.addSlide();
      slide.addText('Executive Summary & Firmographics', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x:0.5, y:0.85, w: '90%', h:0, line: COLOR_BRAND });
      
      // Summary Box - Height restricted to prevent overlap, shrinkText handles overflow
      slide.addText(data.summary, { 
        x: 0.5, y: 1.0, w: '90%', h: 1.3, 
        fontSize: 12, color: COLOR_TEXT, italic: true, valign: 'top', 
        shrinkText: true 
      });
      
      const firmRows = [
        ['Metric', 'Value'],
        ['Size', data.firmographics.companySize],
        ['Revenue', data.firmographics.revenueRange],
        ['Facilities', data.firmographics.facilitiesCount],
        ['Location', data.firmographics.geographicPresence]
      ];
      // Table pushed down to y=2.6 to avoid overlap
      slide.addTable(firmRows, { x: 0.5, y: 2.6, w: 9.0, fontSize: 12, border: { pt: 1, color: 'e5e7eb' }, fill: { color: 'f3f4f6' } });
      
      // --- Slide 3: Operational Profile ---
      slide = pres.addSlide();
      slide.addText('Operational Profile & Risks', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x:0.5, y:0.85, w: '90%', h:0, line: COLOR_BRAND });

      slide.addText('Risk Environment:', { x: 0.5, y: 1.2, fontSize: 14, bold: true });
      slide.addText(data.operationalIndicators.riskEnvironment, { x: 3.5, y: 1.2, fontSize: 14, color: 'dc2626' });

      slide.addText('Key Compliance Standards:', { x: 0.5, y: 1.8, fontSize: 14, bold: true });
      const complianceItems = data.operationalIndicators.complianceStandards.map(s => ({ text: s }));
      slide.addText(complianceItems, { x: 0.5, y: 2.1, w: 4.0, h: 3.0, fontSize: 12, bullet: true, valign: 'top' });

      slide.addText('Operating Conditions:', { x: 5.0, y: 1.8, fontSize: 14, bold: true });
      const opConditions = data.operationalIndicators.operatingConditions.map(c => ({ text: c }));
      slide.addText(opConditions, { x: 5.0, y: 2.1, w: 4.5, h: 3.0, fontSize: 12, bullet: true, valign: 'top' });

      // --- Slide 4: Buying Signals & Urgency (With Chart) ---
      slide = pres.addSlide();
      slide.addText('Buying Signals & Triggers', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x:0.5, y:0.85, w: '90%', h:0, line: COLOR_BRAND });

      // Calculate Urgency Distribution for Chart
      const urgencies = { High: 0, Medium: 0, Low: 0 };
      data.buyingSignals.forEach(s => {
        if (s.urgency === 'High') urgencies.High++;
        else if (s.urgency === 'Medium') urgencies.Medium++;
        else urgencies.Low++;
      });
      const chartDataUrgency = [{
        name: "Urgency",
        labels: ["High", "Medium", "Low"],
        values: [urgencies.High, urgencies.Medium, urgencies.Low]
      }];

      // Signals List (Left Side) - limited to top 4 to fit
      let currentY = 1.2;
      data.buyingSignals.slice(0, 4).forEach((sig) => {
        slide.addText(sig.signal, { x: 0.5, y: currentY, w: 5.5, fontSize: 14, bold: true, color: COLOR_BRAND });
        slide.addText(`Urgency: ${sig.urgency}`, { x: 4.5, y: currentY, w: 2.0, fontSize: 11, color: sig.urgency === 'High' ? 'dc2626' : 'd97706', bold: true });
        slide.addText(sig.description, { x: 0.5, y: currentY + 0.35, w: 6.0, h: 0.8, fontSize: 11, color: COLOR_TEXT, valign: 'top' });
        currentY += 1.2;
      });

      // Chart (Right Side)
      if (data.buyingSignals.length > 0) {
        slide.addChart(pres.ChartType.doughnut, chartDataUrgency, { 
          x: 6.8, y: 1.5, w: 3.0, h: 3.0,
          showLegend: true, 
          legendPos: 'b',
          chartColors: ['dc2626', 'd97706', '16a34a'] // Red, Amber, Green
        });
        slide.addText("Signal Urgency Mix", { x: 6.8, y: 1.2, w: 3.0, align: 'center', fontSize: 12, bold: true, color: COLOR_TEXT });
      }

      // --- Slide 5: Strategic Approach & Product Fit (With Chart) ---
      slide = pres.addSlide();
      slide.addText('Strategic Approach & Product Fit', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x:0.5, y:0.85, w: '90%', h:0, line: COLOR_BRAND });

      // Column 1: Strategy
      slide.addText('Recommended Strategy:', { x: 0.5, y: 1.2, fontSize: 14, bold: true, color: 'd97706' });
      const strategyItems = data.recommendedApproach.map(rec => ({ text: rec, options: { breakLine: true } }));
      slide.addText(strategyItems, { 
        x: 0.5, y: 1.5, w: 4.5, h: 3.5, 
        fontSize: 11, color: COLOR_TEXT, bullet: { code: '2022' }, valign: 'top' 
      });

      // Column 2: Products
      slide.addText('High Priority Products:', { x: 5.2, y: 1.2, fontSize: 14, bold: true, color: '15803d' });
      const productItems = data.productFit.highPriority.map(prod => ({ text: prod, options: { breakLine: true } }));
      slide.addText(productItems, { 
        x: 5.2, y: 1.5, w: 4.5, h: 2.0, 
        fontSize: 11, color: COLOR_TEXT, bullet: { code: '2022' }, valign: 'top' 
      });

      // Bottom Chart: Product Opportunity Count
      const productCounts = [{
        name: "Opportunity Scale",
        labels: ["High Priority", "Medium Priority", "Cross-Sell"],
        values: [
            data.productFit.highPriority.length, 
            data.productFit.mediumPriority.length, 
            data.productFit.crossSell.length
        ]
      }];

      slide.addChart(pres.ChartType.bar, productCounts, {
        x: 5.2, y: 3.8, w: 4.5, h: 1.8,
        chartColors: ['15803d', '6b7280', '3b82f6'],
        showLegend: false,
        barDir: 'col',
        title: 'Product Category Mix'
      });

      pres.writeFile({ fileName: `ICP-${data.targetName.replace(/\s+/g, '-')}.pptx` });

    } catch (err) {
      console.error("PPT export failed", err);
      alert("Failed to export Slide Deck.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="relative inline-block text-left no-export">
      <div>
        <button
          onClick={toggleOpen}
          disabled={isExporting}
          className="inline-flex items-center gap-2 justify-center rounded-lg border border-gray-300 shadow-sm px-4 py-2.5 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand disabled:opacity-50 transition-colors"
        >
          {isExporting ? (
            <Loader2 className="w-4 h-4 animate-spin text-brand" />
          ) : (
            <Download className="w-4 h-4 text-gray-500" />
          )}
          <span>Export</span>
          <ChevronDown className="w-4 h-4 text-gray-400" />
        </button>
      </div>

      {isOpen && (
        <div className="absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-50 animate-fade-in-up">
          <div className="py-1" role="menu" aria-orientation="vertical">
            <button
              onClick={handleExportPDF}
              className="group flex w-full items-center px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 hover:text-brand transition-colors"
            >
              <File className="mr-3 h-4 w-4 text-gray-400 group-hover:text-brand" />
              Download PDF
            </button>
            
            <button
              onClick={handleExportWord}
              className="group flex w-full items-center px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 hover:text-blue-600 transition-colors"
            >
              <FileText className="mr-3 h-4 w-4 text-gray-400 group-hover:text-blue-600" />
              Download Word (.doc)
            </button>
            
            <button
              onClick={handleExportPPT}
              className="group flex w-full items-center px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 hover:text-orange-600 transition-colors"
            >
              <Presentation className="mr-3 h-4 w-4 text-gray-400 group-hover:text-orange-600" />
              Download Slides (.pptx)
            </button>

            <button
              onClick={handleExportImage}
              className="group flex w-full items-center px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 hover:text-purple-600 transition-colors"
            >
              <ImageIcon className="mr-3 h-4 w-4 text-gray-400 group-hover:text-purple-600" />
              Download Image (.png)
            </button>
          </div>
        </div>
      )}
      
      {/* Click outside closer could go here, but simplest is just a toggle */}
      {isOpen && (
        <div className="fixed inset-0 z-40 bg-transparent" onClick={() => setIsOpen(false)} />
      )}
    </div>
  );
};