import React, { useState } from 'react';
import { Download, FileText, Image as ImageIcon, Presentation, File, Loader2, ChevronDown } from 'lucide-react';
import { ICPData } from '../types';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import PptxGenJS from 'pptxgenjs';

interface ExportMenuProps {
  data: ICPData;
  elementRef: React.RefObject<HTMLDivElement>;
}

export const ExportMenu: React.FC<ExportMenuProps> = ({ data, elementRef }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const toggleOpen = () => setIsOpen(!isOpen);

  // Helper: Robustly capture element to canvas
  const captureToCanvas = async (element: HTMLElement) => {
    // 1. Save state
    const originalScrollPos = window.scrollY;

    // 2. Scroll to top to ensure no viewport clipping issues
    window.scrollTo(0, 0);

    // 3. Wait a tick for layout to stabilize
    await new Promise(resolve => setTimeout(resolve, 200));

    try {
      // 4. Capture
      // We do NOT set x, y, width, height manually. 
      // html2canvas(element) automatically calculates the bounding box of the element relative to the document.
      // We set useCORS to true to handle external images (if any).
      // We must NOT set allowTaint: true because we need to read dataURL.
      return await html2canvas(element, {
        scale: 1.5, // Reduced from 2 solely to prevent black image issues
        backgroundColor: '#ffffff',
        useCORS: true,
        logging: false,
        ignoreElements: (el: HTMLElement) => el.classList.contains('no-export'),
        onclone: (clonedDoc: Document) => {

          // Note: html2canvas creates a clone of the document. We need to find the specific element we are capturing within this cloned doc.
          // Since we added an ID 'icp-export-container' to the ref element, we can easily find it.

          const exportContainer = clonedDoc.getElementById('icp-export-container');

          if (exportContainer) {
            const warningDiv = clonedDoc.createElement('div');
            warningDiv.innerHTML = '⚠️ WARNING: This content is generated by AI. Please verify independently.';
            Object.assign(warningDiv.style, {
              backgroundColor: '#fef3c7',
              color: '#92400e',
              border: '1px solid #f59e0b',
              padding: '12px',
              marginBottom: '20px',
              textAlign: 'center',
              fontWeight: 'bold',
              borderRadius: '8px',
              fontFamily: 'sans-serif',
              width: '100%',
              boxSizing: 'border-box'
            });
            exportContainer.insertBefore(warningDiv, exportContainer.firstChild);
          } else if (clonedDoc.body) {
            // Fallback to body
            const warningDiv = clonedDoc.createElement('div');
            warningDiv.innerHTML = '⚠️ WARNING: This content is generated by AI. Please verify independently.';
            Object.assign(warningDiv.style, {
              backgroundColor: '#fef3c7',
              color: '#92400e',
              border: '1px solid #f59e0b',
              padding: '12px',
              marginBottom: '20px',
              textAlign: 'center',
              fontWeight: 'bold',
              borderRadius: '8px',
              fontFamily: 'sans-serif'
            });
            clonedDoc.body.insertBefore(warningDiv, clonedDoc.body.firstChild);
          }

          // Inject Footer (CoE Branding)
          const footerDiv = clonedDoc.createElement('div');
          footerDiv.innerHTML = 'Brought to you by Blackwoods Data & Analytics CoE';
          Object.assign(footerDiv.style, {
            marginTop: '40px',
            marginBottom: '20px',
            textAlign: 'center',
            color: '#4b5563', // gray-600 - Darker for visibility
            fontSize: '14px',
            fontFamily: 'sans-serif',
            fontWeight: '600',
            width: '100%'
          });

          if (exportContainer) {
            exportContainer.appendChild(footerDiv);
            // Ensure container grows to fit footer
            exportContainer.style.height = 'auto';
            exportContainer.style.paddingBottom = '60px'; // Extra buffer
          } else if (clonedDoc.body) {
            clonedDoc.body.appendChild(footerDiv);
          }
        }
        // Ensure we capture the full scroll height of the element if it has overflow, 
        // though typically we are capturing a non-scrolling div on the page.
        // scrollY: -window.scrollY // sometimes needed if not scrolling to top, but we are.
      } as any);
    } catch (e) {
      console.error("Canvas capture error:", e);
      throw e;
    } finally {
      // 5. Restore state
      window.scrollTo(0, originalScrollPos);
    }
  };

  // 1. Export as Image (PNG)
  const handleExportImage = async () => {
    if (!elementRef.current) return;
    setIsExporting(true);
    setIsOpen(false);

    try {
      const canvas = await captureToCanvas(elementRef.current);

      const link = document.createElement('a');
      link.download = `ICP-${data.targetName.replace(/\s+/g, '-')}.jpg`;
      link.href = canvas.toDataURL('image/jpeg', 0.9);
      link.click();
    } catch (err) {
      console.error("Image export failed", err);
      alert("Failed to export image.");
    } finally {
      setIsExporting(false);
    }
  };

  // 2. Export as PDF
  const handleExportPDF = async () => {
    if (!elementRef.current) return;
    setIsExporting(true);
    setIsOpen(false);

    try {
      const canvas = await captureToCanvas(elementRef.current);

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;

      // Create PDF matching the image dimensions (Long PDF style)
      // We convert pixels to points roughly or just use 'px' unit
      const pdf = new jsPDF({
        orientation: imgWidth > imgHeight ? 'landscape' : 'portrait',
        unit: 'px',
        format: [imgWidth, imgHeight]
      });

      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      pdf.save(`ICP-${data.targetName.replace(/\s+/g, '-')}.pdf`);
    } catch (err) {
      console.error("PDF export failed", err);
      alert("Failed to export PDF.");
    } finally {
      setIsExporting(false);
    }
  };

  // 3. Export as Word
  const handleExportWord = () => {
    setIsExporting(true);
    setIsOpen(false);

    try {
      const content = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head><meta charset='utf-8'><title>${data.targetName}</title></head>
        <body style="font-family: Calibri, sans-serif; color: #374151;">
          <div style="background-color: #fef3c7; border: 1px solid #f59e0b; padding: 10px; margin-bottom: 20px; text-align: center; color: #92400e; font-weight: bold;">
            ⚠️ Content generated by AI. Please verify independently.
          </div>
          <h1 style="color: #002452; font-size: 24pt;">ICP Report: ${data.targetName}</h1>
          <p style="color: #6b7280; font-style: italic;">Generated by Blackwoods ICP Intelligence</p>
          <hr/>
          
          <h2 style="color: #002452; border-bottom: 1px solid #ccc;">Company Profile</h2>
          <p>${data.summary}</p>
          
          <h2 style="color: #002452; border-bottom: 1px solid #ccc;">Firmographics</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr><td style="font-weight: bold; width: 30%;">Company Size:</td><td>${data.firmographics.companySize}</td></tr>
            <tr><td style="font-weight: bold;">Revenue:</td><td>${data.firmographics.revenueRange}</td></tr>
            <tr><td style="font-weight: bold;">Sites:</td><td>${data.firmographics.facilitiesCount}</td></tr>
            <tr><td style="font-weight: bold;">Location:</td><td>${data.firmographics.geographicPresence}</td></tr>
            <tr><td style="font-weight: bold;">Industries:</td><td>${data.industryVerticals.join(', ')}</td></tr>
          </table>

          <h2 style="color: #002452; border-bottom: 1px solid #ccc;">Operational Profile</h2>
          <p><strong>PPE Workforce:</strong> ${data.operationalIndicators.workforceSizePPE}</p>
          <p><strong>Risk Environment:</strong> ${data.operationalIndicators.riskEnvironment}</p>
          <p><strong>Operating Conditions:</strong></p>
          <ul>${data.operationalIndicators.operatingConditions?.map(c => `<li>${c}</li>`).join('') || '<li>N/A</li>'}</ul>
          <p><strong>Compliance Standards:</strong></p>
          <ul>${data.operationalIndicators.complianceStandards.map(s => `<li>${s}</li>`).join('')}</ul>

          <h2 style="color: #002452; border-bottom: 1px solid #ccc;">Buying Triggers</h2>
          ${data.buyingSignals.map(s => `
            <div style="margin-bottom: 10px;">
              <p><strong>${s.signal}</strong> [${s.urgency}]</p>
              <p style="margin-top: -5px; color: #4b5563;">${s.description}</p>
            </div>
          `).join('')}
          ${data.buyingSignals.length === 0 ? '<p>No specific signals detected.</p>' : ''}

          <h2 style="color: #002452; border-bottom: 1px solid #ccc;">Key Pain Points</h2>
          <ul>${data.keyPainPoints?.map(p => `<li>${p}</li>`).join('') || '<li>None identified</li>'}</ul>

          <h2 style="color: #002452; border-bottom: 1px solid #ccc;">Decision Makers</h2>
          ${data.decisionMakers.map(dm => `
            <p><strong>${dm.role}</strong></p>
            <ul style="margin-top: -5px;">
              <li>Priorities: ${dm.priorities.join(', ')}</li>
              <li>Pain Points: ${dm.painPoints.join(', ')}</li>
            </ul>
          `).join('')}

          <h2 style="color: #002452; border-bottom: 1px solid #ccc;">Product Fit</h2>
          <p><strong>High Priority:</strong></p>
          <ul>${data.productFit.highPriority.map(p => `<li>${p}</li>`).join('')}</ul>
          <p><strong>Medium Priority:</strong> ${data.productFit.mediumPriority.join(', ')}</p>
          <p><strong>Cross-Sell Opportunities:</strong> ${data.productFit.crossSell.join(', ')}</p>

          <h2 style="color: #002452; border-bottom: 1px solid #ccc;">Recommended Strategy</h2>
          <ul>${data.recommendedApproach.map(r => `<li>${r}</li>`).join('')}</ul>

          <div style="margin-top: 40px; margin-bottom: 20px; text-align: center; color: #4b5563; font-size: 11pt; font-weight: 600;">
            Brought to you by Blackwoods Data & Analytics CoE
          </div>
        </body>
        </html>
      `;
      const blob = new Blob(['\ufeff', content], { type: 'application/msword' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `ICP-${data.targetName.replace(/\s+/g, '-')}.doc`;
      link.click();
    } finally {
      setIsExporting(false);
    }
  };

  // 4. Export as PowerPoint (7-Slide Structure to prevent overflow)
  const handleExportPPT = () => {
    setIsExporting(true);
    setIsOpen(false);

    try {
      const pres = new PptxGenJS();
      pres.layout = 'LAYOUT_16x9';

      const COLOR_BRAND = '002452';
      const COLOR_ACCENT = 'fbbf24';
      const COLOR_TEXT = '374151';

      // --- Slide 1: Title ---
      let slide = pres.addSlide();
      slide.background = { color: COLOR_BRAND };

      // AI Warning Banner on Title Slide
      slide.addText('⚠️ Content generated by AI. Please verify independently.', {
        x: 0, y: 0.2, w: '100%', h: 0.5,
        fontSize: 14, color: 'FFD700', align: 'center', bold: true, fill: { color: '333333' }
      });

      slide.addText(data.targetName, { x: 0.5, y: '40%', w: '90%', fontSize: 36, color: 'FFFFFF', align: 'center', bold: true });
      slide.addText('Ideal Customer Profile Intelligence', { x: 0.5, y: '55%', w: '90%', fontSize: 18, color: COLOR_ACCENT, align: 'center' });
      slide.addText('Brought to you by Blackwoods Data & Analytics CoE', { x: 0, y: '90%', w: '100%', fontSize: 12, color: 'E5E7EB', align: 'center' });

      // --- Slide 2: Company Profile (Missing section fix) ---
      slide = pres.addSlide();
      slide.addText('Brought to you by Blackwoods Data & Analytics CoE', { x: 0, y: '92%', w: '100%', fontSize: 11, color: '6B7280', align: 'center' });
      slide.addText('Company Profile', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x: 0.5, y: 0.85, w: '90%', h: 0, line: { color: COLOR_BRAND, width: 1 } });
      slide.addText(data.summary, {
        x: 0.5, y: 1.2, w: '90%', h: 4.0,
        fontSize: 14, color: COLOR_TEXT, italic: true, valign: 'top', shrinkText: true
      });

      // --- Slide 3: Firmographics ---
      slide = pres.addSlide();
      slide.addText('Brought to you by Blackwoods Data & Analytics CoE', { x: 0, y: '92%', w: '100%', fontSize: 11, color: '6B7280', align: 'center' });
      slide.addText('Firmographics & Scale', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x: 0.5, y: 0.85, w: '90%', h: 0, line: { color: COLOR_BRAND, width: 1 } });

      const firmRows = [
        ['Metric', 'Detail'],
        ['Company Size', data.firmographics.companySize],
        ['Revenue Range', data.firmographics.revenueRange],
        ['Facilities/Sites', data.firmographics.facilitiesCount],
        ['Geographic Presence', data.firmographics.geographicPresence]
      ].map(row => row.map(text => ({ text })));

      slide.addTable(firmRows, { x: 0.5, y: 1.2, w: 9.0, fontSize: 14, border: { pt: 1, color: 'e5e7eb' }, fill: { color: 'f3f4f6' } });

      slide.addText('Core Industries:', { x: 0.5, y: 4.0, fontSize: 14, bold: true });
      slide.addText(data.industryVerticals.join(', '), { x: 0.5, y: 4.4, w: 9.0, fontSize: 12, color: COLOR_TEXT });

      // --- Slide 4: Operational Profile ---
      slide = pres.addSlide();
      slide.addText('Brought to you by Blackwoods Data & Analytics CoE', { x: 0, y: '92%', w: '100%', fontSize: 11, color: '6B7280', align: 'center' });
      slide.addText('Operational Profile & Risk', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x: 0.5, y: 0.85, w: '90%', h: 0, line: { color: COLOR_BRAND, width: 1 } });

      slide.addText('Risk Environment:', { x: 0.5, y: 1.2, fontSize: 14, bold: true, color: 'dc2626' });
      slide.addText(data.operationalIndicators.riskEnvironment, { x: 0.5, y: 1.5, w: 9.0, fontSize: 12 });

      slide.addText('Operating Conditions:', { x: 0.5, y: 2.2, fontSize: 14, bold: true });
      const opConds = data.operationalIndicators.operatingConditions.map(c => ({ text: c }));
      slide.addText(opConds, { x: 0.5, y: 2.5, w: 4.5, h: 2.5, fontSize: 11, bullet: true, valign: 'top' });

      slide.addText('Compliance Standards:', { x: 5.2, y: 2.2, fontSize: 14, bold: true });
      const standards = data.operationalIndicators.complianceStandards.map(s => ({ text: s }));
      slide.addText(standards, { x: 5.2, y: 2.5, w: 4.3, h: 2.5, fontSize: 11, bullet: true, valign: 'top' });

      // --- Slide 5: Buying Signals (With Chart) ---
      slide = pres.addSlide();
      slide.addText('Brought to you by Blackwoods Data & Analytics CoE', { x: 0, y: '92%', w: '100%', fontSize: 11, color: '6B7280', align: 'center' });
      slide.addText('Buying Signals & Urgency', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x: 0.5, y: 0.85, w: '90%', h: 0, line: { color: COLOR_BRAND, width: 1 } });

      const urgencies = { High: 0, Medium: 0, Low: 0 };
      data.buyingSignals.forEach(s => {
        if (s.urgency === 'High') urgencies.High++;
        else if (s.urgency === 'Medium') urgencies.Medium++;
        else urgencies.Low++;
      });

      // Chart
      slide.addChart(pres.ChartType.doughnut, [{
        name: 'Urgency', labels: ['High', 'Med', 'Low'], values: [urgencies.High, urgencies.Medium, urgencies.Low]
      }], { x: 6.5, y: 1.2, w: 3.0, h: 3.0, showLegend: true, legendPos: 'b', chartColors: ['dc2626', 'd97706', '16a34a'] });

      // List
      let currentY = 1.2;
      data.buyingSignals.slice(0, 3).forEach(sig => {
        slide.addText(`${sig.signal} [${sig.urgency}]`, { x: 0.5, y: currentY, w: 5.5, fontSize: 13, bold: true, color: COLOR_BRAND });
        slide.addText(sig.description, { x: 0.5, y: currentY + 0.3, w: 5.5, h: 0.8, fontSize: 10, color: COLOR_TEXT, valign: 'top', shrinkText: true });
        currentY += 1.3;
      });

      // --- Slide 6: Decision Makers ---
      slide = pres.addSlide();
      slide.addText('Brought to you by Blackwoods Data & Analytics CoE', { x: 0, y: '92%', w: '100%', fontSize: 11, color: '6B7280', align: 'center' });
      slide.addText('Key Decision Makers', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x: 0.5, y: 0.85, w: '90%', h: 0, line: { color: COLOR_BRAND, width: 1 } });

      currentY = 1.2;
      data.decisionMakers.forEach(dm => {
        slide.addText(dm.role, { x: 0.5, y: currentY, w: 9.0, fontSize: 14, bold: true, color: COLOR_BRAND });
        slide.addText(`Priorities: ${dm.priorities.join(', ')}`, { x: 0.5, y: currentY + 0.3, w: 9.0, fontSize: 11, color: COLOR_TEXT });
        currentY += 0.9;
      });

      // --- Slide 7: Strategy & Product Fit (With Chart) ---
      slide = pres.addSlide();
      slide.addText('Brought to you by Blackwoods Data & Analytics CoE', { x: 0, y: '92%', w: '100%', fontSize: 11, color: '6B7280', align: 'center' });
      slide.addText('Strategic Fit & Opportunities', { x: 0.5, y: 0.4, fontSize: 24, color: COLOR_BRAND, bold: true });
      slide.addShape(pres.ShapeType.line, { x: 0.5, y: 0.85, w: '90%', h: 0, line: { color: COLOR_BRAND, width: 1 } });

      slide.addText('Sales Approach:', { x: 0.5, y: 1.2, fontSize: 14, bold: true, color: 'd97706' });
      const approaches = data.recommendedApproach.map(a => ({ text: a }));
      slide.addText(approaches, { x: 0.5, y: 1.5, w: 4.5, h: 3.5, fontSize: 11, bullet: true, valign: 'top', shrinkText: true });

      slide.addText('Product Priorities:', { x: 5.2, y: 1.2, fontSize: 14, bold: true, color: '15803d' });
      const products = data.productFit.highPriority.map(p => ({ text: p }));
      slide.addText(products, { x: 5.2, y: 1.5, w: 4.3, h: 2.0, fontSize: 10, bullet: true, valign: 'top' });

      slide.addChart(pres.ChartType.bar, [{
        name: 'Scale', labels: ['High', 'Med', 'Cross'], values: [data.productFit.highPriority.length, data.productFit.mediumPriority.length, data.productFit.crossSell.length]
      }], { x: 5.2, y: 3.8, w: 4.3, h: 1.5, chartColors: ['15803d', '6b7280', '3b82f6'], barDir: 'col' });

      pres.writeFile({ fileName: `ICP-${data.targetName.replace(/\s+/g, '-')}.pptx` });
    } catch (err) {
      console.error(err);
      alert("Failed to export Slide Deck.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="relative inline-block text-left no-export">
      <button
        onClick={toggleOpen}
        disabled={isExporting}
        className="inline-flex items-center gap-2 justify-center rounded-lg border border-gray-300 shadow-sm px-4 py-2.5 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        {isExporting ? <Loader2 className="w-4 h-4 animate-spin text-brand" /> : <Download className="w-4 h-4 text-gray-500" />}
        <span>Export</span>
        <ChevronDown className="w-4 h-4 text-gray-400" />
      </button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-50 overflow-hidden">
            <button onClick={handleExportPDF} className="flex w-full items-center px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 border-b border-gray-100">
              <File className="mr-3 h-4 w-4 text-gray-400" /> Download PDF
            </button>
            <button onClick={handleExportPPT} className="flex w-full items-center px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 border-b border-gray-100">
              <Presentation className="mr-3 h-4 w-4 text-gray-400" /> Download Slides (.pptx)
            </button>
            <button onClick={handleExportWord} className="flex w-full items-center px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 border-b border-gray-100">
              <FileText className="mr-3 h-4 w-4 text-gray-400" /> Download Word (.doc)
            </button>
            <button onClick={handleExportImage} className="flex w-full items-center px-4 py-3 text-sm text-gray-700 hover:bg-gray-50">
              <ImageIcon className="mr-3 h-4 w-4 text-gray-400" /> Download Image (.png)
            </button>
          </div>
        </>
      )}
    </div>
  );
};